defaults:
    addr: :8080
    sirena_client_id: 2285
    sirena_host: 194.84.25.50
    sirena_port: 34323
    redis_host: 127.0.0.1
    redis_port: 6379
    redis_password:
    redis_db:
    client_public_key: Client.Public.key.pem
    client_private_key: Client.Private.key.pem
    client_private_key_password:
    server_public_key: Server.Public.key.pem
    sentry_enable: true
    sentry_dsn: https://7b00887b8296433ab7154351f96de934:2282c9518e334de489f167bb3bc10d05@sentry.io/1364864
