defaults:
    addr: localhost:8080
    sirena_proxy_url: https://sirena-proxy-dev.tmc24.teamcsrv.com/proxy
    redis_host: 127.0.0.1
    redis_port: 6379
    redis_password:
    redis_db:
    pubsub:
      host: "localhost:8085" # local pubsub
      project_id: "tmconsulting24"
      topic: "provider-logs-dev"
      subscription: "provider-logs-receiver-dev"
      key: ""
      timeout: 15 # connection timeout in seconds
    formats:
      time: "2006-01-02T15:04:05"
      date: "2006-01-02"
    sentry_enable: true
    sentry_dsn: https://7b00887b8296433ab7154351f96de934:2282c9518e334de489f167bb3bc10d05@sentry.io/1364864
